version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: "no" #on-failure
    ports:
      - "9000:9000"
    volumes: 
      - .:/app
      - /app/node_modules
